[2024-09-20 07:56:26,100] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_and_store_amazon_books.create_table 2024-09-20T07:51:48.816382+00:00 [queued]>
[2024-09-20 07:56:26,116] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_and_store_amazon_books.create_table 2024-09-20T07:51:48.816382+00:00 [queued]>
[2024-09-20 07:56:26,116] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-09-20 07:56:26,116] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2024-09-20 07:56:26,116] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-09-20 07:56:26,125] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_table> on 2024-09-20T07:51:48.816382+00:00
[2024-09-20 07:56:26,132] {standard_task_runner.py:52} INFO - Started process 63 to run task
[2024-09-20 07:56:26,136] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_and_store_amazon_books', 'create_table', '2024-09-20T07:51:48.816382+00:00', '--job-id', '152', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpnlmpjvq3', '--error-file', '/tmp/tmpog81p4qh']
[2024-09-20 07:56:26,137] {standard_task_runner.py:77} INFO - Job 152: Subtask create_table
[2024-09-20 07:56:26,184] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_and_store_amazon_books.create_table 2024-09-20T07:51:48.816382+00:00 [running]> on host 007eb76872bf
[2024-09-20 07:56:26,229] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_and_store_amazon_books
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-09-20T07:51:48.816382+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-20T07:51:48.816382+00:00
[2024-09-20 07:56:26,229] {postgres.py:69} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS books (
        id SERIAL PRIMARY KEY,
        title TEXT NOT NULL,
        authors TEXT,
        price TEXT,
        rating TEXT
    );
    
[2024-09-20 07:56:26,238] {base.py:74} INFO - Using connection to: id: books_connection. Host: 172.18.0.3, Port: 5432, Schema: amazon_books, Login: airflow, Password: XXXXXXXX, extra: None
[2024-09-20 07:56:26,240] {taskinstance.py:1455} ERROR - could not connect to server: Connection refused
	Is the server running on host "172.18.0.3" and accepting
	TCP/IP connections on port 5432?
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "172.18.0.3" and accepting
	TCP/IP connections on port 5432?

[2024-09-20 07:56:26,244] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=create_table, execution_date=20240920T075148, start_date=20240920T075626, end_date=20240920T075626
[2024-09-20 07:56:26,306] {local_task_job.py:146} INFO - Task exited with return code 1
